
STATUS_NOT_COMPLETE = -1
STATUS_TIME_LIMIT_EXCEDED = 1100
STATUS_MEMORY_LIMIT_EXCEDED = 1200
STATUS_WRONG_ANSWER = 1300
STATUS_ACCEPTED = 1400

COMPILER_PYTHON3 = 'python3'
COMPILER_CPP = 'cpp17'
COMPILER_JAVA = 'java'

COMPILERS = [
    COMPILER_PYTHON3,
    COMPILER_CPP,
    COMPILER_JAVA
]

VERSIONS = {
    COMPILER_PYTHON3: 4,
    COMPILER_CPP: 0,
    COMPILER_JAVA: 4
}

COMPILERS_PUBLIC = [
    ("Python 3", COMPILER_PYTHON3),
    ("C++", COMPILER_CPP),
    ("Java", COMPILER_JAVA)
]
