
STATUS_NOT_COMPLETE = -1
STATUS_TIME_LIMIT_EXCEDED = 1100
STATUS_MEMORY_LIMIT_EXCEDED = 1200
STATUS_WRONG_ANSWER = 1300
STATUS_ACCEPTED = 1400

COMPILER_PYTHON3 = 'python3'
COMPILER_CPP = 'cpp17'
COMPILER_JAVA = 'java'

COMPILERS = ['python3', 'cpp17', 'java']

VERSIONS = {'python3':4,'cpp17':0, 'java':4}